-- 코드를 입력하세요
SELECT  C.CAR_ID , C.CAR_TYPE , ROUND(30 * C.DAILY_FEE * (1-P.DISCOUNT_RATE /100) , 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE ='SUV')
  AND P.DURATION_TYPE LIKE '30일%'
  AND CAR_ID NOT IN (
     SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE END_DATE >= TO_DATE('2022-11-01'  , 'YYYY-MM-DD')
      AND START_DATE <= TO_DATE('2022-11-30' , 'YYYY-MM-DD')
  )
  AND ROUND(30* C.DAILY_FEE * (1 - P.DISCOUNT_RATE/100), 0) BETWEEN 500000 AND 2000000
  ORDER BY FEE DESC , CAR_TYPE ASC , CAR_ID DESC