WITH GROUP_JULY AS
(SELECT FLAVOR , SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY GROUP BY FLAVOR)

SELECT A.FLAVOR
FROM FIRST_HALF AS A
JOIN 
(SELECT B.FLAVOR, (B.TOTAL_ORDER + C.TOTAL_ORDER) AS TOTAL_ORDER
FROM GROUP_JULY AS B
JOIN FIRST_HALF AS C
ON B.FLAVOR = C.FLAVOR) AS D
ON A.FLAVOR = D.FLAVOR
ORDER BY D.TOTAL_ORDER DESC
LIMIT 3