-- 코드를 입력하세요
SELECT 
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    TO_CHAR(RR.REVIEW_DATE, 'YYYY-mm-dd') AS REVIEW_DATE
FROM 
    MEMBER_PROFILE MP
JOIN 
    REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE 
    RR.MEMBER_ID = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        FETCH FIRST 1 ROW ONLY
    )
ORDER BY 
    RR.REVIEW_DATE ASC,
    RR.REVIEW_TEXT ASC;