SELECT T.ID AS ID , N.FISH_NAME AS FISH_NAME , T.LENGTH AS LENGTH
FROM(
   SELECT ID , FISH_TYPE , LENGTH, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC , ID ASC) AS RN FROM FISH_INFO WHERE LENGTH IS NOT NULL
) AS T 
JOIN FISH_NAME_INFO AS N
ON N.FISH_TYPE = T.FISH_TYPE
WHERE T.RN = 1
ORDER BY ID;