-- 코드를 작성해주세요
SELECT 
    SUM_GRADE.SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM (
    SELECT 
        EMP_NO,
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) AS SUM_GRADE
JOIN HR_EMPLOYEES E ON SUM_GRADE.EMP_NO = E.EMP_NO
WHERE SUM_GRADE.SCORE = (
    SELECT 
        MAX(SUM_SCORE)
    FROM (
        SELECT 
            EMP_NO,
            SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) AS SCORES
);